# Generated by Django 3.2 on 2023-03-28 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(verbose_name='День в расписании')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('duration', models.TimeField(verbose_name='Продолжительность')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='timetables.classroom', verbose_name='Кабинет (если есть)')),
                ('groups', models.ManyToManyField(related_name='activities', to='timetables.Group', verbose_name='Группа(ы)')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='timetables.teacher', verbose_name='Преподователь(если ведет)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
