# Generated by Django 3.2 on 2023-03-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0003_auto_20230329_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='describe',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание мероприятия'),
        ),
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наименование мероприятия'),
        ),
    ]
