# Generated by Django 3.2 on 2023-03-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0004_auto_20230329_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
