# Generated by Django 3.2 on 2023-03-30 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetables', '0007_auto_20230330_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='number',
            field=models.CharField(max_length=128, unique=True, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Наименование дисциплины'),
        ),
        migrations.AlterField(
            model_name='methodist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleMethodist', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleTeacher', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
