# Generated by Django 3.2 on 2023-03-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0008_auto_20230330_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Наименование группы'),
        ),
    ]
