# Generated by Django 3.2 on 2023-03-31 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0010_auto_20230331_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='business_trip_end',
            field=models.DateField(default=datetime.date(2023, 3, 31), verbose_name='Дата окончания командировки'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='business_trip_start',
            field=models.DateField(default=datetime.date(2023, 3, 31), verbose_name='Дата начала командировки'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='vacation_end',
            field=models.DateField(default=datetime.date(2023, 3, 31), verbose_name='Дата окончания отпуска'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='vacation_start',
            field=models.DateField(default=datetime.date(2023, 3, 31), verbose_name='Дата начала отпуска'),
        ),
    ]
