# Generated by Django 3.2 on 2023-03-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0012_auto_20230331_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='business_trip_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания командировки'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='business_trip_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала командировки'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='vacation_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания отпуска'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='vacation_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала отпуска'),
        ),
    ]
